spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    #database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: system
    password: system
